"use client";

import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DashboardData } from "../types/dashboard.types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/design-system/ui/card";

export function DashboardCharts({ revenue, orderStatuses }: Pick<DashboardData, "revenue" | "orderStatuses">) {
  const colors = ["var(--chart-2)", "var(--chart-3)", "var(--chart-4)", "var(--chart-5)"];
  return <div className="grid gap-4 xl:grid-cols-3"><Card className="rounded-2xl shadow-none xl:col-span-2"><CardHeader className="flex-row items-start justify-between pb-0"><div><CardTitle className="font-heading text-base">Revenue overview</CardTitle><CardDescription className="text-[11px]">Gross sales, last 12 months</CardDescription></div><div className="flex gap-1.5"><span className="rounded-lg bg-primary/10 px-3 py-1.5 text-[10px] font-bold text-primary">Revenue</span><span className="rounded-lg bg-muted px-3 py-1.5 text-[10px] font-semibold text-muted-foreground">Orders</span></div></CardHeader><CardContent className="h-[250px] px-3 pb-3"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue} margin={{ top: 18, right: 12, left: 0, bottom: 0 }}><defs><linearGradient id="dashboard-revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--chart-1)" stopOpacity={0.26} /><stop offset="1" stopColor="var(--chart-1)" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} fontSize={10} /><YAxis hide /><Tooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--border)", borderRadius: 12, fontSize: 12 }} formatter={(value) => [`$${Number(value).toLocaleString()}`, "Revenue"]} /><Area type="monotone" dataKey="revenue" stroke="var(--chart-1)" fill="url(#dashboard-revenue-fill)" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></CardContent></Card><Card className="rounded-2xl shadow-none"><CardHeader className="pb-0"><CardTitle className="font-heading text-base">Order status</CardTitle><CardDescription className="text-[11px]">This month</CardDescription></CardHeader><CardContent><div className="relative mx-auto h-40 w-40"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={orderStatuses} dataKey="value" nameKey="name" innerRadius={48} outerRadius={72} strokeWidth={0}>{orderStatuses.map((item, index) => <Cell key={item.name} fill={colors[index]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="font-heading text-xl font-bold">3,842</p><p className="text-[10px] text-muted-foreground">orders</p></div></div></div><div className="mt-1 space-y-2">{orderStatuses.map((item, index) => <div key={item.name} className="flex items-center gap-2 text-xs"><span className="size-2 rounded-sm" style={{ background: colors[index] }} /><span className="flex-1 text-muted-foreground">{item.name}</span><span className="font-bold">{item.value}%</span></div>)}</div></CardContent></Card></div>;
}
