import Link from "next/link";
import { ChevronRight, TriangleAlert } from "lucide-react";
import type { DashboardData } from "../types/dashboard.types";
import { formatCurrency } from "@/core/utils/currency";
import { StatusBadge } from "@/components/status/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/design-system/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/design-system/ui/table";

function statusVariant(status: string) { if (["Paid","Completed","Shipped"].includes(status)) return "success" as const; if (["Pending","Processing"].includes(status)) return "warning" as const; return "danger" as const; }

export function OperationsPanels({ recentOrders, topProducts, lowStock }: Pick<DashboardData, "recentOrders" | "topProducts" | "lowStock">) {
  return <div className="grid gap-4 xl:grid-cols-3"><Card className="overflow-hidden rounded-2xl shadow-none xl:col-span-2"><CardHeader className="flex-row items-center justify-between py-4"><CardTitle className="font-heading text-base">Recent orders</CardTitle><Link href="/orders" className="flex items-center text-xs font-bold text-primary">View all<ChevronRight className="size-4" /></Link></CardHeader><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/60"><TableHead>Order</TableHead><TableHead>Customer</TableHead><TableHead>Payment</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{recentOrders.map((order) => <TableRow key={order.id}><TableCell><Link href={`/orders/${order.id}`} className="font-mono text-[11px] font-bold text-primary">#{order.id}</Link></TableCell><TableCell className="text-xs font-medium">{order.customer}</TableCell><TableCell><StatusBadge variant={statusVariant(order.paymentStatus)}>{order.paymentStatus}</StatusBadge></TableCell><TableCell><StatusBadge variant={statusVariant(order.status)}>{order.status}</StatusBadge></TableCell><TableCell className="text-right font-heading text-xs font-bold">{formatCurrency(order.total)}</TableCell></TableRow>)}</TableBody></Table></div></Card><div className="space-y-4"><Card className="rounded-2xl shadow-none"><CardHeader className="pb-2"><CardTitle className="font-heading text-base">Top products</CardTitle></CardHeader><CardContent className="space-y-1">{topProducts.map((product) => <div key={product.id} className="flex items-center gap-3 py-2"><div className="size-10 shrink-0 rounded-[10px]" style={{ background: `repeating-linear-gradient(45deg,${product.color},${product.color} 4px,color-mix(in srgb,${product.color} 80%,white) 4px,color-mix(in srgb,${product.color} 80%,white) 8px)` }} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{product.name}</p><p className="text-[10px] text-muted-foreground">{product.sales} sold</p></div><span className="font-heading text-xs font-bold">{formatCurrency(product.revenue)}</span></div>)}</CardContent></Card><Card className="rounded-2xl shadow-none"><CardHeader className="flex-row items-center justify-between pb-2"><CardTitle className="font-heading text-base">Low stock</CardTitle><span className="rounded-full bg-warning/10 px-2.5 py-1 text-[10px] font-bold text-warning">7 items</span></CardHeader><CardContent>{lowStock.map((product) => <div key={product.id} className="flex items-center gap-2 py-2"><TriangleAlert className="size-4 text-warning" /><span className="min-w-0 flex-1 truncate text-xs font-medium">{product.name}</span><span className="text-xs font-bold text-warning">{product.stock} left</span></div>)}</CardContent></Card></div></div>;
}
