import type { RouteDescriptor } from "@platform/plugin-sdk";

/**
 * Versioned descriptors for the live NestJS CRM core API. Dynamic state-action
 * routes perform their final action-specific permission check inside the service.
 */
export const crmRoutes = [
  { id: "crm.dashboard", method: "GET", path: "/api/v1/crm/dashboard", permission: "crm.dashboard.view" },
  { id: "crm.search", method: "GET", path: "/api/v1/crm/search", permission: "crm.search" },
  { id: "crm.reports", method: "GET", path: "/api/v1/crm/reports", permission: "crm.reports.view" },

  { id: "crm.leads.list", method: "GET", path: "/api/v1/crm/leads", permission: "crm.leads.view" },
  { id: "crm.leads.create", method: "POST", path: "/api/v1/crm/leads", permission: "crm.leads.create" },
  { id: "crm.leads.get", method: "GET", path: "/api/v1/crm/leads/:id", permission: "crm.leads.view" },
  { id: "crm.leads.update", method: "PATCH", path: "/api/v1/crm/leads/:id", permission: "crm.leads.update" },
  { id: "crm.leads.assign", method: "POST", path: "/api/v1/crm/leads/:id/assign", permission: "crm.leads.assign" },
  { id: "crm.leads.delete", method: "DELETE", path: "/api/v1/crm/leads/:id", permission: "crm.leads.delete" },
  { id: "crm.leads.convert", method: "POST", path: "/api/v1/crm/leads/:id/convert", permission: "crm.leads.convert" },

  { id: "crm.customers.list", method: "GET", path: "/api/v1/crm/customers", permission: "crm.customers.view" },
  { id: "crm.customers.create", method: "POST", path: "/api/v1/crm/customers", permission: "crm.customers.create" },
  { id: "crm.customers.get", method: "GET", path: "/api/v1/crm/customers/:id", permission: "crm.customers.view" },
  { id: "crm.customers.update", method: "PATCH", path: "/api/v1/crm/customers/:id", permission: "crm.customers.update" },
  { id: "crm.customers.delete", method: "DELETE", path: "/api/v1/crm/customers/:id", permission: "crm.customers.delete" },
  { id: "crm.customers.timeline", method: "GET", path: "/api/v1/crm/customers/:id/timeline", permission: "crm.customers.view" },

  { id: "crm.contacts.list", method: "GET", path: "/api/v1/crm/contacts", permission: "crm.contacts.view" },
  { id: "crm.contacts.create", method: "POST", path: "/api/v1/crm/contacts", permission: "crm.contacts.create" },
  { id: "crm.contacts.get", method: "GET", path: "/api/v1/crm/contacts/:id", permission: "crm.contacts.view" },
  { id: "crm.contacts.update", method: "PATCH", path: "/api/v1/crm/contacts/:id", permission: "crm.contacts.update" },
  { id: "crm.contacts.delete", method: "DELETE", path: "/api/v1/crm/contacts/:id", permission: "crm.contacts.delete" },

  { id: "crm.pipelines.list", method: "GET", path: "/api/v1/crm/pipelines", permission: "crm.opportunities.view" },
  { id: "crm.pipelines.create", method: "POST", path: "/api/v1/crm/pipelines", permission: "crm.settings.manage" },
  { id: "crm.pipelines.update", method: "PATCH", path: "/api/v1/crm/pipelines/:id", permission: "crm.settings.manage" },
  { id: "crm.pipeline-stages.create", method: "POST", path: "/api/v1/crm/pipelines/:id/stages", permission: "crm.settings.manage" },
  { id: "crm.pipeline-stages.update", method: "PATCH", path: "/api/v1/crm/pipeline-stages/:id", permission: "crm.settings.manage" },
  { id: "crm.pipeline-stages.delete", method: "DELETE", path: "/api/v1/crm/pipeline-stages/:id", permission: "crm.settings.manage" },
  { id: "crm.opportunities.list", method: "GET", path: "/api/v1/crm/opportunities", permission: "crm.opportunities.view" },
  { id: "crm.opportunities.create", method: "POST", path: "/api/v1/crm/opportunities", permission: "crm.opportunities.create" },
  { id: "crm.opportunities.get", method: "GET", path: "/api/v1/crm/opportunities/:id", permission: "crm.opportunities.view" },
  { id: "crm.opportunities.update", method: "PATCH", path: "/api/v1/crm/opportunities/:id", permission: "crm.opportunities.update" },
  { id: "crm.opportunities.assign", method: "POST", path: "/api/v1/crm/opportunities/:id/assign", permission: "crm.opportunities.assign" },
  { id: "crm.opportunities.delete", method: "DELETE", path: "/api/v1/crm/opportunities/:id", permission: "crm.opportunities.delete" },
  { id: "crm.opportunities.stage", method: "PATCH", path: "/api/v1/crm/opportunities/:id/stage", permission: "crm.opportunities.update" },
  { id: "crm.opportunities.close", method: "POST", path: "/api/v1/crm/opportunities/:id/close", permission: "crm.opportunities.update" },

  { id: "crm.activities.list", method: "GET", path: "/api/v1/crm/activities", permission: "crm.activities.view" },
  { id: "crm.activities.create", method: "POST", path: "/api/v1/crm/activities", permission: "crm.activities.create" },
  { id: "crm.activities.update", method: "PATCH", path: "/api/v1/crm/activities/:id", permission: "crm.activities.update" },
  { id: "crm.activities.delete", method: "DELETE", path: "/api/v1/crm/activities/:id", permission: "crm.activities.delete" },
  { id: "crm.tasks.list", method: "GET", path: "/api/v1/crm/tasks", permission: "crm.tasks.view" },
  { id: "crm.tasks.create", method: "POST", path: "/api/v1/crm/tasks", permission: "crm.tasks.create" },
  { id: "crm.tasks.update", method: "PATCH", path: "/api/v1/crm/tasks/:id", permission: "crm.tasks.update" },
  { id: "crm.tasks.delete", method: "DELETE", path: "/api/v1/crm/tasks/:id", permission: "crm.tasks.delete" },
  { id: "crm.communications.list", method: "GET", path: "/api/v1/crm/communications", permission: "crm.communications.view" },
  { id: "crm.communications.create", method: "POST", path: "/api/v1/crm/communications", permission: "crm.communications.create" },

  { id: "crm.notes.list", method: "GET", path: "/api/v1/crm/notes", permission: "crm.notes.view" },
  { id: "crm.notes.create", method: "POST", path: "/api/v1/crm/notes", permission: "crm.notes.create" },
  { id: "crm.notes.update", method: "PATCH", path: "/api/v1/crm/notes/:id", permission: "crm.notes.update" },
  { id: "crm.notes.delete", method: "DELETE", path: "/api/v1/crm/notes/:id", permission: "crm.notes.delete" },
  { id: "crm.tags.list", method: "GET", path: "/api/v1/crm/tags", permission: "crm.notes.view" },
  { id: "crm.tags.create", method: "POST", path: "/api/v1/crm/tags", permission: "crm.notes.create" },
  { id: "crm.tags.assign", method: "POST", path: "/api/v1/crm/tags/:id/assign", permission: "crm.notes.update" },
  { id: "crm.tags.unassign", method: "POST", path: "/api/v1/crm/tags/:id/unassign", permission: "crm.notes.update" },
  { id: "crm.attachments.list", method: "GET", path: "/api/v1/crm/attachments", permission: "crm.attachments.view" },
  { id: "crm.attachments.create", method: "POST", path: "/api/v1/crm/attachments", permission: "crm.attachments.create" },
  { id: "crm.attachments.delete", method: "DELETE", path: "/api/v1/crm/attachments/:id", permission: "crm.attachments.delete" },
  { id: "crm.custom-fields.list", method: "GET", path: "/api/v1/crm/custom-fields", permission: "crm.custom_fields.view" },
  { id: "crm.custom-fields.upsert", method: "POST", path: "/api/v1/crm/custom-fields", permission: "crm.custom_fields.manage" },
  { id: "crm.custom-field-values.set", method: "PUT", path: "/api/v1/crm/custom-field-values", permission: "crm.custom_fields.manage" },
  { id: "crm.custom-field-values.get", method: "GET", path: "/api/v1/crm/custom-field-values/:entityType/:entityId", permission: "crm.custom_fields.view" },

  { id: "crm.proposals.list", method: "GET", path: "/api/v1/crm/proposals", permission: "crm.proposals.view" },
  { id: "crm.proposals.create", method: "POST", path: "/api/v1/crm/proposals", permission: "crm.proposals.create" },
  { id: "crm.proposals.get", method: "GET", path: "/api/v1/crm/proposals/:id", permission: "crm.proposals.view" },
  { id: "crm.proposals.update", method: "PATCH", path: "/api/v1/crm/proposals/:id", permission: "crm.proposals.update" },
  { id: "crm.proposals.delete", method: "DELETE", path: "/api/v1/crm/proposals/:id", permission: "crm.proposals.delete" },
  { id: "crm.proposals.action", method: "POST", path: "/api/v1/crm/proposals/:id/actions/:action", permission: "crm.proposals.send" },
  { id: "crm.estimates.list", method: "GET", path: "/api/v1/crm/estimates", permission: "crm.estimates.view" },
  { id: "crm.estimates.create", method: "POST", path: "/api/v1/crm/estimates", permission: "crm.estimates.create" },
  { id: "crm.estimates.get", method: "GET", path: "/api/v1/crm/estimates/:id", permission: "crm.estimates.view" },
  { id: "crm.estimates.update", method: "PATCH", path: "/api/v1/crm/estimates/:id", permission: "crm.estimates.update" },
  { id: "crm.estimates.delete", method: "DELETE", path: "/api/v1/crm/estimates/:id", permission: "crm.estimates.delete" },
  { id: "crm.estimates.action", method: "POST", path: "/api/v1/crm/estimates/:id/actions/:action", permission: "crm.estimates.send" },
  { id: "crm.estimates.convert", method: "POST", path: "/api/v1/crm/estimates/:id/convert", permission: "crm.invoices.create" },
  { id: "crm.invoices.list", method: "GET", path: "/api/v1/crm/invoices", permission: "crm.invoices.view" },
  { id: "crm.invoices.create", method: "POST", path: "/api/v1/crm/invoices", permission: "crm.invoices.create" },
  { id: "crm.invoices.get", method: "GET", path: "/api/v1/crm/invoices/:id", permission: "crm.invoices.view" },
  { id: "crm.invoices.update", method: "PATCH", path: "/api/v1/crm/invoices/:id", permission: "crm.invoices.update" },
  { id: "crm.invoices.delete", method: "DELETE", path: "/api/v1/crm/invoices/:id", permission: "crm.invoices.delete" },
  { id: "crm.invoices.action", method: "POST", path: "/api/v1/crm/invoices/:id/actions/:action", permission: "crm.invoices.send" },
  { id: "crm.payments.list", method: "GET", path: "/api/v1/crm/payments", permission: "crm.invoices.view" },
  { id: "crm.payments.create", method: "POST", path: "/api/v1/crm/payments", permission: "crm.invoices.record_payment" },
  { id: "crm.contracts.list", method: "GET", path: "/api/v1/crm/contracts", permission: "crm.contracts.view" },
  { id: "crm.contracts.create", method: "POST", path: "/api/v1/crm/contracts", permission: "crm.contracts.create" },
  { id: "crm.contracts.get", method: "GET", path: "/api/v1/crm/contracts/:id", permission: "crm.contracts.view" },
  { id: "crm.contracts.update", method: "PATCH", path: "/api/v1/crm/contracts/:id", permission: "crm.contracts.update" },
  { id: "crm.contracts.delete", method: "DELETE", path: "/api/v1/crm/contracts/:id", permission: "crm.contracts.delete" },

  { id: "crm.ticket-departments.list", method: "GET", path: "/api/v1/crm/ticket-departments", permission: "crm.tickets.view" },
  { id: "crm.ticket-departments.create", method: "POST", path: "/api/v1/crm/ticket-departments", permission: "crm.settings.manage" },
  { id: "crm.tickets.list", method: "GET", path: "/api/v1/crm/tickets", permission: "crm.tickets.view" },
  { id: "crm.tickets.create", method: "POST", path: "/api/v1/crm/tickets", permission: "crm.tickets.create" },
  { id: "crm.tickets.get", method: "GET", path: "/api/v1/crm/tickets/:id", permission: "crm.tickets.view" },
  { id: "crm.tickets.update", method: "PATCH", path: "/api/v1/crm/tickets/:id", permission: "crm.tickets.update" },
  { id: "crm.tickets.assign", method: "POST", path: "/api/v1/crm/tickets/:id/assign", permission: "crm.tickets.assign" },
  { id: "crm.tickets.close", method: "POST", path: "/api/v1/crm/tickets/:id/close", permission: "crm.tickets.close" },
  { id: "crm.ticket-messages.create", method: "POST", path: "/api/v1/crm/tickets/:id/messages", permission: "crm.tickets.update" },
  { id: "crm.notifications.list", method: "GET", path: "/api/v1/crm/notifications", permission: "crm.notifications.view" },
  { id: "crm.notifications.create", method: "POST", path: "/api/v1/crm/notifications", permission: "crm.notifications.create" },
  { id: "crm.notifications.retry", method: "POST", path: "/api/v1/crm/notifications/:id/retry", permission: "crm.notifications.retry" },

  { id: "crm.settings.get", method: "GET", path: "/api/v1/crm/settings", permission: "crm.settings.view" },
  { id: "crm.settings.upsert", method: "PUT", path: "/api/v1/crm/settings", permission: "crm.settings.manage" },
  { id: "crm.imports.list", method: "GET", path: "/api/v1/crm/imports", permission: "crm.imports.view" },
  { id: "crm.imports.create", method: "POST", path: "/api/v1/crm/imports", permission: "crm.imports.create" },
  { id: "crm.exports.list", method: "GET", path: "/api/v1/crm/exports", permission: "crm.exports.view" },
  { id: "crm.exports.create", method: "POST", path: "/api/v1/crm/exports", permission: "crm.exports.create" },
  { id: "crm.transfer-jobs.get", method: "GET", path: "/api/v1/crm/transfer-jobs/:id", permission: "crm.imports.view" },
  { id: "crm.external-references.list", method: "GET", path: "/api/v1/crm/integrations/external-references", permission: "crm.integrations.view" },
  { id: "crm.external-references.upsert", method: "POST", path: "/api/v1/crm/integrations/external-references", permission: "crm.integrations.manage" },
  { id: "crm.external-references.delete", method: "DELETE", path: "/api/v1/crm/integrations/external-references/:id", permission: "crm.integrations.manage" },
] as const satisfies readonly RouteDescriptor[];
