import {
  evalleyDarkTheme,
  evalleyLightTheme,
} from "@/design-system/themes/evalley-theme";
import { defaultClient } from "./default.client";
import type { ClientConfig } from "./client.types";

export const evalleyClient: ClientConfig = {
  public: {
    ...defaultClient.public,
    key: "evalley",
    theme: {
      light: evalleyLightTheme,
      dark: evalleyDarkTheme,
      fontSans: "Geist",
      fontHeading: "Geist",
    },
    brand: {
      name: "Evalley Administration",
      shortName: "Evalley",
      description: "Marketplace operations center",
      logo: "/brands/evalley/icon.png",
      icon: "/brands/evalley/icon.png",
      favicon: "/brands/evalley/favicon.ico",
      loginArtwork: "/brands/evalley/login-artwork.png",
    },
    layout: {
      ...defaultClient.public.layout,
      defaultType: "sidebar",
      allowedTypes: ["sidebar"],
    },
    modules: [
      "dashboard",
      "analytics",
      "products",
      "variants",
      "attributes",
      "inventory",
      "categories",
      "promotions",
      "reviews",
      "content",
      "orders",
      "returns",
      "shipments",
      "customers",
      "vendors",
      "withdrawals",
      "ledger",
      "crm",
      "crmLeads",
      "crmCustomers",
      "modules",
      "settings",
    ],
    availableModules: [
      "dashboard",
      "analytics",
      "products",
      "variants",
      "attributes",
      "inventory",
      "categories",
      "promotions",
      "reviews",
      "content",
      "orders",
      "returns",
      "shipments",
      "customers",
      "vendors",
      "withdrawals",
      "ledger",
      "marketing",
      "shipping",
      "reports",
      "users",
      "crm",
      "crmLeads",
      "crmCustomers",
      "modules",
      "settings",
    ],
    features: { ...defaultClient.public.features, layoutSwitcher: false },
  },
  server: {
    api: {
      ...defaultClient.server.api,
      baseUrl: "http://143.198.211.47:9090/api/v1/admin",
      adapter: "standard",
    },
    auth: { adapter: "ecommerce-api" },
  },
};
