import {
  ArchiveRestore,
  BarChart3,
  Boxes,
  Building2,
  CalendarCheck,
  ChartNoAxesCombined,
  ClipboardList,
  FileSignature,
  FileText,
  FolderTree,
  LayoutDashboard,
  Megaphone,
  PackageSearch,
  Puzzle,
  Settings,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Store,
  Truck,
  UserRoundCog,
  Users,
  UsersRound,
  WalletCards,
  Warehouse,
  Wrench,
  Contact,
  UserPlus,
} from "lucide-react";
import type { AdminModuleDefinition } from "./module.types";

export const moduleRegistry: AdminModuleDefinition[] = [
  { key: "dashboard", label: "Dashboard", description: "Business overview", href: "/dashboard", icon: LayoutDashboard, navigationGroup: "Overview", order: 10, permission: "dashboard.read" },
  { key: "analytics", label: "Analytics", href: "/analytics", icon: BarChart3, navigationGroup: "Overview", order: 20, permission: "analytics.read" },
  { key: "products", label: "Products", description: "Catalog management", href: "/products", icon: PackageSearch, navigationGroup: "Catalog", order: 30, permission: "products.read" },
  { key: "variants", label: "Variants", href: "/variants", icon: Boxes, navigationGroup: "Catalog", order: 40, permission: "variants.read" },
  { key: "attributes", label: "Attributes & Options", href: "/attributes", icon: SlidersHorizontal, navigationGroup: "Catalog", order: 50, permission: "attributes.read" },
  { key: "inventory", label: "Inventory", href: "/inventory", icon: Warehouse, navigationGroup: "Catalog", order: 60, permission: "inventory.read" },
  { key: "categories", label: "Categories & Brands", href: "/categories", icon: FolderTree, navigationGroup: "Catalog", order: 70, permission: "categories.read" },
  { key: "promotions", label: "Flash Sales & Discounts", href: "/promotions", icon: Megaphone, navigationGroup: "Catalog", order: 80, permission: "promotions.read" },
  { key: "reviews", label: "Reviews", href: "/reviews", icon: Star, navigationGroup: "Catalog", order: 90, permission: "reviews.read", badge: "12" },
  { key: "content", label: "Content", description: "Storefront banners, pages & footer", href: "/content", icon: FileText, navigationGroup: "Catalog", order: 95, permission: "content.read" },
  { key: "orders", label: "Orders", href: "/orders", icon: ShoppingCart, navigationGroup: "Sales", order: 100, permission: "orders.read", badge: "24" },
  { key: "returns", label: "Returns", href: "/returns", icon: ArchiveRestore, navigationGroup: "Sales", order: 110, permission: "returns.read", badge: "5" },
  { key: "shipments", label: "Shipments", href: "/shipments", icon: Truck, navigationGroup: "Sales", order: 120, permission: "shipments.read" },
  { key: "customers", label: "Customers", href: "/customers", icon: Users, navigationGroup: "Sales", order: 130, permission: "customers.read" },
  { key: "vendors", label: "Vendors", href: "/vendors", icon: Store, navigationGroup: "Marketplace", order: 140, permission: "vendors.read" },
  { key: "withdrawals", label: "Withdrawals", href: "/withdrawals", icon: WalletCards, navigationGroup: "Marketplace", order: 150, permission: "withdrawals.read", badge: "3" },
  { key: "ledger", label: "Commission ledger", href: "/ledger", icon: ClipboardList, navigationGroup: "Marketplace", order: 160, permission: "ledger.read" },
  { key: "marketing", label: "Marketing", href: "/marketing", icon: BarChart3, navigationGroup: "Growth", order: 170, permission: "marketing.read" },
  { key: "shipping", label: "Shipping", href: "/shipping", icon: Truck, navigationGroup: "Operations", order: 180, permission: "shipping.read" },
  { key: "reports", label: "Reports", href: "/reports", icon: ChartNoAxesCombined, navigationGroup: "Insights", order: 190, permission: "reports.read" },
  { key: "properties", label: "Properties", href: "/properties", icon: Building2, navigationGroup: "Portfolio", order: 30, permission: "properties.read" },
  { key: "bookings", label: "Bookings", href: "/bookings", icon: CalendarCheck, navigationGroup: "Leasing", order: 40, permission: "bookings.read" },
  { key: "tenants", label: "Tenants", href: "/tenants", icon: UsersRound, navigationGroup: "Leasing", order: 50, permission: "tenants.read" },
  { key: "leases", label: "Leases", href: "/leases", icon: FileSignature, navigationGroup: "Leasing", order: 60, permission: "leases.read" },
  { key: "payments", label: "Payments", href: "/payments", icon: WalletCards, navigationGroup: "Finance", order: 70, permission: "payments.read" },
  { key: "maintenance", label: "Maintenance", href: "/maintenance", icon: Wrench, navigationGroup: "Operations", order: 80, permission: "maintenance.read" },
  { key: "crm", label: "CRM", description: "Customer relationships", href: "/crm", icon: Contact, navigationGroup: "CRM", order: 205, permission: "crm.dashboard.view" },
  { key: "crmLeads", label: "Leads", href: "/crm/leads", icon: UserPlus, navigationGroup: "CRM", order: 206, permission: "crm.leads.view" },
  { key: "crmCustomers", label: "Customers", description: "CRM accounts & contacts", href: "/crm/customers", icon: UsersRound, navigationGroup: "CRM", order: 207, permission: "crm.customers.view" },
  { key: "users", label: "Users", href: "/users", icon: UserRoundCog, navigationGroup: "Administration", order: 200, permission: "users.read" },
  { key: "modules", label: "Module Add-ons", description: "Enable client capabilities", href: "/modules", icon: Puzzle, navigationGroup: "System", order: 210, permission: "modules.manage" },
  { key: "settings", label: "Settings", href: "/settings", icon: Settings, navigationGroup: "System", order: 220, permission: "settings.read" },
];
